- shell: echo $SHELL
- usb: lsusb
- release: lsb_release -a
- alias: alias lll='ll --group-directories-first'
- alias: alias celsius="paste <(cat /sys/class/thermal/thermal_zone*/type) <(cat /sys/class/thermal/thermal_zone*/temp) | column -s $'\t' -t | sed 's/\(.\)..$/.\1°C/'"
- youtube_dl: youtube-dl --extract-audio --audio-format mp3 -o 'FOLDER/playlist/%(title)s.%(ext)s' url
- delete, line_beginning: CTRL-U
- delete, line_end: CTRL-K
- filesystem, move_rename: mv old_file new_file
- filesystem, remove_directory: rm -R folder
- filesystem, remove_file: rm filename
- keyboard, events_start: xev
- keyboard, events_end: CTRL-C
- keymap, settings: setxkbmap -print -verbose 10
- keymap, file: /usr/share/X11/xkd/symbols
- keymap, list: xmodmap -pke
- move, line_beginning: CTRL-A
- move, line_end: CTRL-E
- tar, gz: tar -zxvf filename.gz
- tar, xz: tar -xvf filename.xz
- gem, list: gem list
- gem, list: gem list | grep github
- gem, uninstall: gem uninstall addressable --version 2.6.0
- gem, update: gem update github-pages
- bashrc, source: ". ~/.bashrc"
- apt-get, purge:  sudo apt-get purge ...
- install, run:
  - cd folder/file.run
  - chmod -x file.run
  - ./file.run
- versions, linux: lsb_release -a > Ubuntu 18.04.2 LTS bionic
- architecture, add: sudo dpkg --add-architecture i386
- architecture, list: dpkg --print-foreign-architectures
- architecture, remove: sudo dpkg --remove-architecture i368
- fonts: fc-match -a
- history, list: history
- history, execute command n: "!n"
- history, execute last command: "!!"
- rvm, warning: "`rvm reset` for the last warning"
- virtual_terminal, keys: CTRL+ALT+F(1-6)
- virtual_terminal, open: sudo chvt 3
- virtual_terminal, close: chvt 2
- virtual_terminal, configure: sudo dpkg-reconfigure console-setup
- virtual_terminal, apply: setupcon
- virtual_terminal, list: who -la
- virtual_terminal, open: kill xxxx
- debian, install: "sudo dpkg -i filename.deb"