- shell: echo $SHELL
- usb: lsusb
- release: lsb_release -a
- alias: alias lll='ll --group-directories-first'
- youtube_dl: youtube-dl --extract-audio --audio-format mp3 -o 'FOLDER/playlist/%(title)s.%(ext)s' url
- delete, line_beginning: CTRL-U
- delete, line_end: CTRL-K
- filesystem, move_rename: mv old_file new_file
- filesystem, remove_directory: rm -R folder
- filesystem, remove_file: rm filename
- keyboard, events_start: xev
- keyboard, events_end: CTRL-C
- settings, print: setxkbmap -print -verbose 10
- keymap, file: /usr/share/X11/xkd/symbols
- keymap, list: xmodmap -pke
- move, line_beginning: CTRL-A
- move, line_end: CTRL-E
- tar, gz: tar -zxvf filename.gz
- tar, xz: tar -xvf filename.xz
- gem, list: gem list
- gem, list: gem list | grep github
- gem, uninstall: gem uninstall addressable --version 2.6.0
